name = "website"
compatibility_date = "2025-11-06"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

